baseURL: https://graphql.workshops.fauna.com/
languageCode: en-us
title: Getting started with Fauna and GraphQL

theme: hugo-theme-learn

params:
  # Change default color scheme with a variant one. Optional: can also be one of "red", "blue", or "green".
  themeVariant: "fauna"
  # themeVariant: "fauna-dark"

  disableLandingPageButton: false
  disableMermaid: true
  showVisitedLinks: true

menu:
  shortcuts:
    - name: <i class='fas fa-fw fa-book'></i> Fauna Docs
      identifier: docs
      url: https://docs.fauna.com/fauna/current/api/graphql/
      weight: 10
    - name: <i class='fas fa-fw fa-flask'></i> Fauna Labs
      identifier: labs
      url: https://github.com/fauna-labs/
      weight: 20
    - name: <i class='fab fa-fw fa-github'></i> GitHub repo
      identifier: repo
      url: https://github.com/fauna-labs/zen-of-fauna/
      weight: 30
