baseURL: https://graphql.workshops.fauna.com/
languageCode: en-us
title: Fauna for GraphQL developers

theme: fauna-workshop-theme

# Google Analytics
googleAnalytics: "UA-51914115-2"

params:
  # Change default color scheme with a variant one. Optional: can also be one of "red", "blue", or "green".
  themeVariant: "flora"
  # themeVariant: "flora-dark"

  disableLandingPageButton: false
  disableMermaid: true
  showVisitedLinks: true

  # OpenGraph/Twitter card parameters
  description: Learn how to build applications that scale to any size userbase with GraphQL and Fauna!
  images:
  - images/twitter-card-site-image.png
  title: Fauna for GraphQL developers

outputs:
  home:
    - HTML
    - JSON

menu:
  shortcuts:
    - name: <i class='fas fa-fw fa-book'></i> Fauna Docs
      identifier: docs
      url: https://docs.fauna.com/fauna/current/api/graphql/
      weight: 10
    - name: <i class='fas fa-fw fa-flask'></i> Fauna Labs
      identifier: labs
      url: https://github.com/fauna-labs/
      weight: 20
    - name: <i class='fab fa-fw fa-github'></i> GitHub repo
      identifier: repo
      url: https://github.com/fauna-labs/zen-of-fauna/
      weight: 30
